//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClientService_1295.LayananKonversi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CelCiusToReamurOperationCompleted;
        
        private System.Threading.SendOrPostCallback CelCiusToFahrenheitOperationCompleted;
        
        private System.Threading.SendOrPostCallback CelCiusToKelvinOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::ClientService_1295.Properties.Settings.Default.ClientService_1295_LayananKonversi_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CelCiusToReamurCompletedEventHandler CelCiusToReamurCompleted;
        
        /// <remarks/>
        public event CelCiusToFahrenheitCompletedEventHandler CelCiusToFahrenheitCompleted;
        
        /// <remarks/>
        public event CelCiusToKelvinCompletedEventHandler CelCiusToKelvinCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CelCiusToReamur", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double CelCiusToReamur(int C) {
            object[] results = this.Invoke("CelCiusToReamur", new object[] {
                        C});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void CelCiusToReamurAsync(int C) {
            this.CelCiusToReamurAsync(C, null);
        }
        
        /// <remarks/>
        public void CelCiusToReamurAsync(int C, object userState) {
            if ((this.CelCiusToReamurOperationCompleted == null)) {
                this.CelCiusToReamurOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCelCiusToReamurOperationCompleted);
            }
            this.InvokeAsync("CelCiusToReamur", new object[] {
                        C}, this.CelCiusToReamurOperationCompleted, userState);
        }
        
        private void OnCelCiusToReamurOperationCompleted(object arg) {
            if ((this.CelCiusToReamurCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CelCiusToReamurCompleted(this, new CelCiusToReamurCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CelCiusToFahrenheit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double CelCiusToFahrenheit(int C) {
            object[] results = this.Invoke("CelCiusToFahrenheit", new object[] {
                        C});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void CelCiusToFahrenheitAsync(int C) {
            this.CelCiusToFahrenheitAsync(C, null);
        }
        
        /// <remarks/>
        public void CelCiusToFahrenheitAsync(int C, object userState) {
            if ((this.CelCiusToFahrenheitOperationCompleted == null)) {
                this.CelCiusToFahrenheitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCelCiusToFahrenheitOperationCompleted);
            }
            this.InvokeAsync("CelCiusToFahrenheit", new object[] {
                        C}, this.CelCiusToFahrenheitOperationCompleted, userState);
        }
        
        private void OnCelCiusToFahrenheitOperationCompleted(object arg) {
            if ((this.CelCiusToFahrenheitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CelCiusToFahrenheitCompleted(this, new CelCiusToFahrenheitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CelCiusToKelvin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CelCiusToKelvin(int C) {
            object[] results = this.Invoke("CelCiusToKelvin", new object[] {
                        C});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CelCiusToKelvinAsync(int C) {
            this.CelCiusToKelvinAsync(C, null);
        }
        
        /// <remarks/>
        public void CelCiusToKelvinAsync(int C, object userState) {
            if ((this.CelCiusToKelvinOperationCompleted == null)) {
                this.CelCiusToKelvinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCelCiusToKelvinOperationCompleted);
            }
            this.InvokeAsync("CelCiusToKelvin", new object[] {
                        C}, this.CelCiusToKelvinOperationCompleted, userState);
        }
        
        private void OnCelCiusToKelvinOperationCompleted(object arg) {
            if ((this.CelCiusToKelvinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CelCiusToKelvinCompleted(this, new CelCiusToKelvinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CelCiusToReamurCompletedEventHandler(object sender, CelCiusToReamurCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CelCiusToReamurCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CelCiusToReamurCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CelCiusToFahrenheitCompletedEventHandler(object sender, CelCiusToFahrenheitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CelCiusToFahrenheitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CelCiusToFahrenheitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CelCiusToKelvinCompletedEventHandler(object sender, CelCiusToKelvinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CelCiusToKelvinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CelCiusToKelvinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591